services:
  backend:
    build: .
    user: root
    expose:
      - "8024"
    environment:
      - DOMAIN_NAME
      - SUB_DOMAIN_NAME
      - CI_PROJECT_NAME
      - CI_SERVER_HOST
      - CI_PROJECT_PATH
      - CI_REGISTRY_IMAGE
      - IMAGE_VERSION
      - BITRIX_INBOUND_URL
      - PG_CARVALIMA_HELPDESK_DBNAME
      - PG_BOTAPP_HOST
      - PG_BOTAPP_PASSWORD
      - PG_BOTAPP_PORT
      - PG_BOTAPP_USER
      - WEBMAIL_USUARIO
      - WEBMAIL_SENHA
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helpdesk.rule=Host(`${SUB_DOMAIN_NAME}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.helpdesk.entrypoints=websecure"
      - "traefik.http.routers.helpdesk.tls=true"
      - "traefik.http.services.helpdesk.loadbalancer.server.port=8024"
    networks:
      - traefik

networks:
  traefik:
    external: true

